version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  reviewers:
    - "daveshanley"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  reviewers:
    - "daveshanley"